version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    network_mode: "host"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
  spiders:
    build: ./spiders
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
    restart: on-failure
    network_mode: "host"
<<<<<<< HEAD
  downloader:
    build: ./downloader
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
    restart: on-failure
    network_mode: "host"
=======
>>>>>>> 3c9e8c348f0d13286f4db15f7ef26a65e60baf40

